import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="w-full h-full m-0 overflow-hidden" lang="en">
      <body className={`${inter.className} w-full h-full m-0 overflow-hidden`}>
        {children}
      </body>
    </html>
  );
}
